import BackgroundManager from "@/app/components/BackgroundManager";
import WeatherProvider from "@/app/provider/weatherProvider";
import { inter } from "@/app/ui/fonts";
import Sidebar from "@/app/ui/weather/Sidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.className}>
            <body className="antialiased ">
                <WeatherProvider>
                    <BackgroundManager />
                    <div className="flex flex-col md:flex-row md:overflow-hidden h-screen">
                        <div className="w-full flex-none md:w-64">
                            <Sidebar />
                        </div>
                        <div className="grow md:overflow-y-auto ">
                            {children}
                        </div>
                    </div>
                </WeatherProvider>
            </body>
        </html>
    );
}
