import WeatherProvider from "@/app/provider/weatherProvider";
import Sidebar from "@/app/ui/weather/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url(/weather/background/rain-bg.jpg)] bg-cover bg-no-repeat bg-center`}
            >
                <WeatherProvider>
                    <div className="flex flex-col md:flex-row md:overflow-hidden h-screen">
                        <div className="w-full flex-none md:w-64">
                            <Sidebar />
                        </div>
                        <div className="grow p-6 md:overflow-y-auto md:p-12">
                            {children}
                        </div>
                    </div>
                </WeatherProvider>
            </body>
        </html>
    );
}
